import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import {fileURLToPath} from "node:url";

const scriptPath=fileURLToPath(import.meta.url);
const root=path.resolve(path.dirname(scriptPath),"..");
const defaultConfigPath=path.join(root,"config/youtube-sources.json");
const defaultVideosPath=path.join(root,"js/data/videos.js");
const defaultContentPath=path.join(root,"content/videos.json");
const apiRoot="https://www.googleapis.com/youtube/v3";

function assert(condition,message){
  if(!condition)throw new Error(message);
}

function cleanText(value,maxLength=240){
  return String(value??"").replace(/\s+/g," ").trim().slice(0,maxLength);
}

export function parseDurationSeconds(value){
  const match=String(value??"").match(/^P(?:(\d+)D)?T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?$/);
  if(!match)throw new Error("Unsupported YouTube duration: "+value);
  return Math.round(
    Number(match[1]||0)*86400+
    Number(match[2]||0)*3600+
    Number(match[3]||0)*60+
    Number(match[4]||0)
  );
}

export function matchesSource(video,source){
  const text=(cleanText(video?.snippet?.title)+" "+cleanText(video?.snippet?.description,5000)).toLowerCase();
  const includes=source.includeTerms.map(term=>term.toLowerCase());
  const excludes=source.excludeTerms.map(term=>term.toLowerCase());
  return (includes.length===0||includes.some(term=>text.includes(term)))&&!excludes.some(term=>text.includes(term));
}

export function normalizeVideo(video,source,longformThresholdSeconds){
  const durationSeconds=parseDurationSeconds(video.contentDetails.duration);
  return {
    id:"yt_"+video.id,
    type:"yt",
    vid:video.id,
    title:cleanText(video.snippet.title,180),
    creator:cleanText(video.snippet.channelTitle||source.label,100),
    long:durationSeconds>=longformThresholdSeconds,
    durationSeconds,
    publishedAt:video.snippet.publishedAt,
    sourceHandle:source.handle,
    automated:true
  };
}

export function selectAutomaticVideos(records,config,manualVideos){
  const seen=new Set(manualVideos.filter(item=>item.type==="yt").map(item=>item.vid));
  return [...records]
    .sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)||a.vid.localeCompare(b.vid))
    .filter(item=>{
      if(seen.has(item.vid))return false;
      seen.add(item.vid);
      return true;
    })
    .slice(0,config.maxAutomaticVideos);
}

function safeJson(value){
  return JSON.stringify(value,null,2).replace(/\u2028/g,"\\u2028").replace(/\u2029/g,"\\u2029");
}

export function renderVideosFile(manual,automatic){
  return `(function(){
  "use strict";

  const manual = ${safeJson(manual)};

  // Generated by scripts/sync-youtube.mjs. Review the automation PR before merging.
  const automatic = ${safeJson(automatic)};
  const freezeItem = item => Object.freeze(item);
  const frozenManual = Object.freeze(manual.map(freezeItem));
  const frozenAutomatic = Object.freeze(automatic.map(freezeItem));

  window.GodotTokVideos = Object.freeze({
    manual: frozenManual,
    automatic: frozenAutomatic,
    all: Object.freeze([...frozenManual, ...frozenAutomatic])
  });
})();
`;
}

export function renderContentFile(automatic){
  return safeJson({version:1,automatic})+"\n";
}

export function validateConfig(config){
  assert(config&&config.version===1,"youtube-sources.json must use version 1.");
  assert(Number.isInteger(config.maxAutomaticVideos)&&config.maxAutomaticVideos>=1&&config.maxAutomaticVideos<=100,"maxAutomaticVideos must be between 1 and 100.");
  assert(Number.isInteger(config.longformThresholdSeconds)&&config.longformThresholdSeconds>=60,"longformThresholdSeconds must be at least 60.");
  assert(Array.isArray(config.sources)&&config.sources.length>0,"At least one YouTube source is required.");
  const handles=new Set();
  for(const source of config.sources){
    assert(/^@[A-Za-z0-9._-]{3,30}$/.test(source.handle),"Invalid YouTube handle: "+source.handle);
    assert(!handles.has(source.handle.toLowerCase()),"Duplicate YouTube handle: "+source.handle);
    handles.add(source.handle.toLowerCase());
    assert(cleanText(source.label).length>0,"Missing label for "+source.handle);
    assert(Number.isInteger(source.scanLimit)&&source.scanLimit>=1&&source.scanLimit<=200,"scanLimit must be between 1 and 200 for "+source.handle);
    assert(Number.isInteger(source.keep)&&source.keep>=1&&source.keep<=source.scanLimit,"keep must be between 1 and scanLimit for "+source.handle);
    assert(Array.isArray(source.includeTerms)&&Array.isArray(source.excludeTerms),"Source terms must be arrays for "+source.handle);
  }
  return config;
}

function loadVideos(videosPath){
  const context=vm.createContext({window:{}});
  vm.runInContext(fs.readFileSync(videosPath,"utf8"),context,{filename:videosPath});
  const data=context.window.GodotTokVideos;
  assert(data&&Array.isArray(data.manual)&&Array.isArray(data.automatic),"Invalid video data file.");
  return JSON.parse(JSON.stringify(data));
}

async function youtubeRequest(resource,params,apiKey,fetchImpl){
  const url=new URL(apiRoot+"/"+resource);
  for(const [key,value] of Object.entries({...params,key:apiKey})){
    if(value!==undefined&&value!==null&&value!=="")url.searchParams.set(key,String(value));
  }
  const response=await fetchImpl(url,{headers:{Accept:"application/json"}});
  if(!response.ok){
    const detail=cleanText(await response.text(),300);
    throw new Error(`YouTube ${resource} request failed with ${response.status}: ${detail}`);
  }
  return response.json();
}

async function resolveUploadsPlaylist(source,apiKey,fetchImpl){
  const response=await youtubeRequest("channels",{
    part:"contentDetails,snippet",
    forHandle:source.handle
  },apiKey,fetchImpl);
  assert(response.items?.length===1,"YouTube channel was not found: "+source.handle);
  const channel=response.items[0];
  const playlistId=channel.contentDetails?.relatedPlaylists?.uploads;
  assert(playlistId,"Uploads playlist was not returned for "+source.handle);
  return {playlistId,channelTitle:channel.snippet?.title||source.label};
}

async function listPlaylistVideoIds(playlistId,scanLimit,apiKey,fetchImpl){
  const ids=[];
  let pageToken;
  while(ids.length<scanLimit){
    const response=await youtubeRequest("playlistItems",{
      part:"contentDetails",
      playlistId,
      maxResults:Math.min(50,scanLimit-ids.length),
      pageToken
    },apiKey,fetchImpl);
    for(const item of response.items??[]){
      const id=item.contentDetails?.videoId;
      if(id)ids.push(id);
    }
    pageToken=response.nextPageToken;
    if(!pageToken||(response.items??[]).length===0)break;
  }
  return ids.slice(0,scanLimit);
}

async function getVideoDetails(ids,apiKey,fetchImpl){
  const videos=[];
  for(let index=0;index<ids.length;index+=50){
    const response=await youtubeRequest("videos",{
      part:"snippet,contentDetails,status",
      id:ids.slice(index,index+50).join(",")
    },apiKey,fetchImpl);
    videos.push(...(response.items??[]));
  }
  return videos;
}

export async function syncYouTube({
  apiKey,
  configPath=defaultConfigPath,
  videosPath=defaultVideosPath,
  contentPath=defaultContentPath,
  fetchImpl=globalThis.fetch,
  write=true
}={}){
  assert(typeof apiKey==="string"&&apiKey.trim().length>0,"YOUTUBE_API_KEY is required.");
  assert(typeof fetchImpl==="function","A Fetch API implementation is required.");
  const config=validateConfig(JSON.parse(fs.readFileSync(configPath,"utf8")));
  const current=loadVideos(videosPath);
  const collected=[];

  for(const source of config.sources){
    const channel=await resolveUploadsPlaylist(source,apiKey,fetchImpl);
    const ids=await listPlaylistVideoIds(channel.playlistId,source.scanLimit,apiKey,fetchImpl);
    const details=await getVideoDetails(ids,apiKey,fetchImpl);
    const accepted=details
      .filter(video=>video.status?.privacyStatus==="public"&&video.status?.embeddable!==false)
      .filter(video=>video.contentDetails?.duration&&matchesSource(video,source))
      .map(video=>normalizeVideo(video,{...source,label:channel.channelTitle},config.longformThresholdSeconds))
      .filter(video=>video.durationSeconds>0)
      .slice(0,source.keep);
    collected.push(...accepted);
    console.log(`${source.handle}: accepted ${accepted.length} of ${details.length} checked uploads.`);
  }

  const automatic=selectAutomaticVideos(collected,config,current.manual);
  const output=renderVideosFile(current.manual,automatic);
  const contentOutput=renderContentFile(automatic);
  const previous=fs.readFileSync(videosPath,"utf8");
  const previousContent=fs.existsSync(contentPath)?fs.readFileSync(contentPath,"utf8"):"";
  const catalogueChanged=output!==previous;
  const contentChanged=contentOutput!==previousContent;
  const changed=catalogueChanged||contentChanged;
  if(write&&catalogueChanged){
    const temporary=videosPath+".tmp";
    fs.writeFileSync(temporary,output,"utf8");
    fs.renameSync(temporary,videosPath);
  }
  if(write&&contentChanged){
    const temporary=contentPath+".tmp";
    fs.mkdirSync(path.dirname(contentPath),{recursive:true});
    fs.writeFileSync(temporary,contentOutput,"utf8");
    fs.renameSync(temporary,contentPath);
  }
  console.log(`YouTube sync selected ${automatic.length} automatic videos. ${changed?"Catalogue changed.":"No catalogue change."}`);
  return {automatic,changed,catalogueChanged,contentChanged,output,contentOutput};
}

async function main(){
  try{
    await syncYouTube({apiKey:process.env.YOUTUBE_API_KEY});
  }catch(error){
    console.error(error instanceof Error?error.message:String(error));
    process.exitCode=1;
  }
}

if(process.argv[1]&&path.resolve(process.argv[1])===scriptPath)await main();
